services:
  spark-iceberg:
    build: ./Iceberg
    depends_on:
      rest:
        condition: service_started
      create-bucket:
        condition: service_completed_successfully
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    expose:
      - 8888
      - 8080
      - 10000
      - 10001
  rest:
    image: tabulario/iceberg-rest
    expose:
      - 8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://rustfs:9000
  rustfs:
    image: rustfs/rustfs:1.0.1@sha256:1803faef57627e2d9c2e7d89d655d712ddded5389040054987163043fecb6a3c
    environment:
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=password
      - RUSTFS_SERVER_DOMAINS=rustfs
    networks:
      default:
        aliases:
          - warehouse.rustfs
    expose:
      - 9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  create-bucket:
    depends_on:
      rustfs:
        condition: service_healthy
    image: amazon/aws-cli:2.27.50@sha256:48c3d4212e2f5b0e24bdc6af7708f9412ce65425a79575e0f78b8f8c0dcd70ab
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    command: ["--endpoint-url", "http://rustfs:9000", "s3", "mb", "s3://warehouse"]
  server:
    depends_on:
      spark-iceberg:
        condition: service_completed_successfully
    volumes:
      - ./Iceberg/data:/data
    environment:
      - START_OPTS=-Xmx4g -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/app.d
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - S3_ENDPOINT=http://rustfs:9000
      - CATALOG_URI=http://rest:8181
      - WAREHOUSE_LOCATION=s3://warehouse/
