io.deephaven.project.ProjectType=DOCKER_REGISTRY
# Even though the image is expected to be bumped from latest, we should correlate that with the specific version number
# for easier reference.
# 8.3.2
deephaven.registry.imageName=confluentinc/cp-kafka:latest
deephaven.registry.imageId=confluentinc/cp-kafka@sha256:5e8f3ab5b4977c9a8fd6137d26af2caad878aca316f24c55f08206217e3cec48
