plugins {
    id 'java-library'
    id 'io.deephaven.project.register'
}

description 'Barrage Benchmark: Benchmarks for Barrage message serialization/deserialization'

sourceSets {
    benchmark {
        java {
            srcDir 'src/benchmark/java'
        }
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

configurations {
    benchmarkImplementation.extendsFrom implementation
    benchmarkRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    benchmarkImplementation project(':extensions-barrage')
    benchmarkImplementation project(':engine-table')
    benchmarkImplementation project(':BenchmarkSupport')
    benchmarkImplementation libs.arrow.vector
    benchmarkImplementation libs.flatbuffers.java
    benchmarkImplementation platform(libs.grpc.bom)
    benchmarkImplementation libs.grpc.api
    benchmarkImplementation TestTools.projectDependency(project, 'engine-rowset')
    benchmarkImplementation TestTools.projectDependency(project, 'engine-table')

    benchmarkAnnotationProcessor libs.jmh.generator.annprocess
    benchmarkCompileOnly libs.jmh.generator.annprocess

    benchmarkRuntimeOnly project(':configs')
    benchmarkRuntimeOnly project(':test-configs')
}

def createJmhTask = {
    taskName, cliArgs, jvmAddArgs=[], heapSize='8g' -> tasks.create(taskName, JavaExec, { JavaExec task ->
        new File("$rootDir/tmp/workspace").mkdirs()
        new File("$rootDir/tmp/logs").mkdirs()

        task.workingDir "$rootDir/tmp/workspace"
        task.classpath = sourceSets.benchmark.runtimeClasspath
        task.mainClass.set 'io.deephaven.benchmarking.runner.BenchmarkRunner'

        // arguments to pass to the application
        def jvmArgs = [ '-DConfiguration.rootFile=dh-tests.prop',
                "-Dworkspace=$rootDir/tmp/workspace",
                '-Dconfiguration.quiet=true',
                '-Djava.awt.headless=true',
                '-DQueryTable.memoizeResults=false',
                "-Xmx$heapSize"
        ]
        jvmArgs.addAll(jvmAddArgs)
        task.jvmArgs jvmArgs
        task.args cliArgs

        return
    })
}

createJmhTask('jmhRunBarrageRoundTrip', 'BarrageMessageRoundTripBenchmark')
