plugins {
    id 'java-library'
    id 'io.deephaven.project.register'
}

description 'Barrage Benchmark: Benchmarks for Barrage message serialization/deserialization'

sourceSets {
    test {
        java {
            srcDir 'src/benchmark/java'
        }
    }
}

test {
    failOnNoDiscoveredTests = false
}

dependencies {
    testImplementation project(':extensions-barrage')
    testImplementation project(':engine-table')
    testImplementation project(':BenchmarkSupport')
    testImplementation libs.arrow.vector
    testImplementation libs.flatbuffers.java
    testImplementation platform(libs.grpc.bom)
    testImplementation libs.grpc.api
    testImplementation TestTools.projectDependency(project, 'engine-rowset')
    testImplementation TestTools.projectDependency(project, 'engine-table')

    testAnnotationProcessor libs.jmh.generator.annprocess
    testCompileOnly libs.jmh.generator.annprocess

    testRuntimeOnly project(':configs')
    testRuntimeOnly project(':test-configs')
}

def createJmhTask = {
    taskName, cliArgs, jvmAddArgs=[], heapSize='8g' -> tasks.create(taskName, JavaExec, { JavaExec task ->
        new File("$rootDir/tmp/workspace").mkdirs()
        new File("$rootDir/tmp/logs").mkdirs()

        task.workingDir "$rootDir/tmp/workspace"
        task.classpath = sourceSets.test.runtimeClasspath
        task.mainClass.set 'io.deephaven.benchmarking.runner.BenchmarkRunner'

        // arguments to pass to the application
        def jvmArgs = [ '-DConfiguration.rootFile=dh-tests.prop',
                "-Dworkspace=$rootDir/tmp/workspace",
                '-Dconfiguration.quiet=true',
                '-Djava.awt.headless=true',
                '-DQueryTable.memoizeResults=false',
                "-Xmx$heapSize"
        ]
        jvmArgs.addAll(jvmAddArgs)
        task.jvmArgs jvmArgs
        task.args cliArgs

        return
    })
}

createJmhTask('jmhRunBarrageRoundTrip', 'BarrageMessageRoundTripBenchmark')
