//
// Copyright (c) 2016-2026 Deephaven Data Labs and Patent Pending
//
package io.deephaven.engine.table.impl.join;

import io.deephaven.base.MathUtil;
import io.deephaven.base.verify.Assert;
import io.deephaven.chunk.IntChunk;
import io.deephaven.chunk.attributes.Any;
import io.deephaven.engine.rowset.RowSequence;
import io.deephaven.engine.table.ColumnSource;
import io.deephaven.engine.table.WritableColumnSource;
import io.deephaven.engine.table.impl.by.typed.TypedHasherFactory;
import io.deephaven.engine.table.impl.sources.InMemoryColumnSource;
import io.deephaven.engine.table.impl.sources.IntegerArraySource;
import io.deephaven.engine.table.impl.sources.immutable.ImmutableIntArraySource;
import it.unimi.dsi.fastutil.ints.IntArrayList;
import org.jetbrains.annotations.NotNull;

import static io.deephaven.engine.table.impl.JoinControl.MAX_TABLE_SIZE;

/**
 * A {@link KeyIdHasher} whose keys can also be {@link #remove(IntChunk) removed}, for state that ticks.
 * <p>
 * A removed key's slot becomes a tombstone and its id is handed to a later insertion, so the ids stay within the peak
 * number of live keys. The table grows into a new main table while the old one becomes an alternate that each later
 * build drains a little at a time, so that no one build pays for rehashing the whole table. A {@link #build} with full
 * rehashes enabled instead rehashes all at once, which is cheaper when nothing is waiting on the result.
 * <p>
 * The typed implementations are generated by {@link TypedHasherFactory}; {@link #make} returns one suitable for the key
 * sources.
 */
public abstract class IncrementalKeyIdHasherTypedBase extends KeyIdHasher {
    /**
     * The alternate slots a partial rehash examines for each entry about to be built. Bounding the slots examined,
     * rather than the live entries moved, keeps one build from scanning a long run of tombstones and empty slots;
     * {@link #computeTableSize} sizes a new table so that the alternate still drains before the new table fills. That
     * requires a maximum load factor greater than {@code 1 / REHASH_SLOTS_PER_ENTRY}: at or below it, a new table the
     * size of the alternate cannot pay for examining every alternate slot once anything is live or being built, so
     * every rehash would double the table. Just above it, the table stabilizes only once it is many times the live
     * entries. The generated hashers refer to this constant, so changing it changes both the drain rate and the sizing.
     */
    public static final int REHASH_SLOTS_PER_ENTRY = 3;

    protected static final int TOMBSTONE_ID = -1;

    // the number of slots in our alternate table, to start with "1" is a lie, but rehashPointer is zero; so our
    // location value is positive and can be compared against rehashPointer safely
    protected int alternateTableSize = 1;

    // how much of the alternate sources are necessary to rehash?
    protected int rehashPointer = 0;

    /** How many keys are in the table, in both main and alternate? */
    protected long liveEntries = 0;
    /** How many slots of the alternate table are occupied, including tombstones? */
    protected long alternateEntries = 0;

    protected final WritableColumnSource[] alternateKeySources;
    protected ImmutableIntArraySource alternateId;

    // the slot, in the main or the alternate table, that holds each id's key
    protected final IntegerArraySource idToSlot = new IntegerArraySource();

    // the ids of removed keys, which are handed out before new ones
    private final IntArrayList freeIds = new IntArrayList();
    // whether any key has been removed, leaving a tombstone that a full rehash must not copy
    private boolean anyRemoved = false;

    // whether the current build rehashes all at once
    private boolean fullRehash = false;

    protected IncrementalKeyIdHasherTypedBase(ColumnSource<?>[] tableKeySources, int tableSize,
            double maximumLoadFactor) {
        super(tableKeySources, tableSize, maximumLoadFactor);
        if (maximumLoadFactor <= 1.0 / REHASH_SLOTS_PER_ENTRY) {
            throw new IllegalArgumentException("maximumLoadFactor " + maximumLoadFactor
                    + " is not greater than 1 / REHASH_SLOTS_PER_ENTRY; a partial rehash could not drain the alternate"
                    + " table before the new table fills");
        }
        alternateKeySources = new WritableColumnSource[tableKeySources.length];
    }

    /**
     * Make a hasher for keys with the types of {@code tableKeySources}.
     *
     * @param tableKeySources sources with the key types; every source later built or probed must have the same chunk
     *        types
     * @param tableSize the initial number of slots, a power of two
     * @param maximumLoadFactor the fraction of the slots that may be occupied before the table grows, greater than
     *        {@code 1 / REHASH_SLOTS_PER_ENTRY}
     * @return a hasher with no keys
     */
    public static IncrementalKeyIdHasherTypedBase make(
            @NotNull final ColumnSource<?>[] tableKeySources,
            final int tableSize,
            final double maximumLoadFactor) {
        return TypedHasherFactory.make(IncrementalKeyIdHasherTypedBase.class, tableKeySources, tableKeySources,
                tableSize, maximumLoadFactor, maximumLoadFactor);
    }

    /**
     * {@link #build(RowSequence, ColumnSource[], IdChunkConsumer) Build}, growing the table by full rehashes rather
     * than incrementally; for a build that nothing is waiting on, such as the initial one.
     * <p>
     * No key may have been {@link #remove(IntChunk) removed} yet. A full rehash copies tombstones along with live keys,
     * in slot order, so it could place a key's tombstone ahead of a live entry for the same key, and a probe for the
     * key would stop at the tombstone.
     */
    public void buildWithFullRehash(
            @NotNull final RowSequence rows,
            @NotNull final ColumnSource<?>[] sources,
            @NotNull final IdChunkConsumer consumer) {
        Assert.eqFalse(anyRemoved, "anyRemoved");
        fullRehash = true;
        try {
            build(rows, sources, consumer);
        } finally {
            fullRehash = false;
        }
    }

    /**
     * Remove the keys with {@code ids} from the table. The ids may be handed to keys added by any later {@link #build},
     * so the caller must have finished with every structure that refers to them.
     *
     * @param ids the distinct ids of keys in the table
     */
    public void remove(final IntChunk<? extends Any> ids) {
        final int size = ids.size();
        for (int ii = 0; ii < size; ++ii) {
            final int id = ids.get(ii);
            final int slot = idToSlot.getInt(id);
            // the key stays in the slot, so that a probe for it stops here rather than searching on
            if (slot < tableSize && mainId.getUnsafe(slot) == id) {
                mainId.set(slot, TOMBSTONE_ID);
            } else {
                Assert.lt(slot, "slot", rehashPointer, "rehashPointer");
                Assert.eq(alternateId.getUnsafe(slot), "alternateId.getUnsafe(slot)", id, "id");
                alternateId.set(slot, TOMBSTONE_ID);
            }
            freeIds.add(id);
        }
        liveEntries -= size;
        anyRemoved |= size > 0;
    }

    @Override
    public long size() {
        return liveEntries;
    }

    @Override
    protected void prepareForChunk(final Context context, final int nextChunkSize) {
        while (doRehash(context, nextChunkSize)) {
            migrateFront();
        }
        idToSlot.ensureCapacity((long) nextId + nextChunkSize);
    }

    @Override
    protected void onChunkBuilt(final Context context, final long entriesAdded) {
        // building takes away from the credit we have built up rehashing; a chunk that adds nothing does not pay
        context.rehashCredits -= Math.toIntExact(entriesAdded);
    }

    @Override
    protected int allocateId(final int slot) {
        final int id = freeIds.isEmpty() ? nextId++ : freeIds.removeInt(freeIds.size() - 1);
        idToSlot.set(id, slot);
        return id;
    }

    /**
     * @param context the context of the build, which holds its rehash credits
     * @param nextChunkSize the size of the chunk about to be built
     * @return true if a front migration is required
     */
    private boolean doRehash(final Context context, final int nextChunkSize) {
        if (rehashPointer > 0) {
            final int requiredRehash = nextChunkSize - context.rehashCredits;
            if (requiredRehash <= 0) {
                return false;
            }

            // before building, we need to do at least as much rehash work as we would do build work
            context.rehashCredits += rehashInternalPartial(requiredRehash);
            if (rehashPointer == 0) {
                clearAlternate();
            }
        }

        if (numEntries + nextChunkSize <= tableSize * maximumLoadFactor) {
            return false;
        }

        final int oldTableSize = tableSize;
        tableSize = computeTableSize(nextChunkSize, oldTableSize);

        // we can't give the caller credit for rehashes with the old table, we need to begin migrating things again
        if (context.rehashCredits > 0) {
            context.rehashCredits = 0;
        }

        if (fullRehash) {
            // we need to ditch the alternate table before continuing on a full rehash
            if (rehashPointer > 0) {
                // a partial rehash is bounded by the slots it examines, so ask for every slot that remains
                rehashInternalPartial(rehashPointer);
                Assert.eqZero(alternateEntries, "alternateEntries");
                clearAlternate();
            }
            rehashInternalFull(oldTableSize);
            return false;
        }
        Assert.eqZero(rehashPointer, "rehashPointer");

        setupNewAlternate(oldTableSize);
        adviseNewAlternate();
        if (liveEntries == 0) {
            // every entry is a tombstone, so nothing needs to migrate; drop the old table rather than examine it
            clearAlternate();
            return false;
        }

        return true;
    }

    /**
     * @param nextChunkSize the size of the chunk about to be built
     * @param alternateSize the size of the table that becomes the alternate
     * @return the size of the new table
     */
    private int computeTableSize(final int nextChunkSize, final int alternateSize) {
        // we use the number of liveEntries multiplied by 2, so that as we rehash we can both consume a slot for the
        // live entry from the alternate table; and also consume a slot for the new value.
        final long desiredEntries = Math.max(liveEntries * 2, liveEntries + nextChunkSize);
        // round up, so that the desired entries fit under the load factor and the table is never full
        long newSize = MathUtil.roundUpPowerOf2(
                Math.max(this.tableSize, (long) Math.ceil(desiredEntries / maximumLoadFactor)));
        // Each build examines REHASH_SLOTS_PER_ENTRY alternate slots per entry before inserting, so the alternate
        // drains before the new table needs another rehash if the entries that fit under the load factor pay for
        // examining every alternate slot. An alternate with no live entries is dropped without being examined.
        if (!fullRehash && liveEntries > 0) {
            while (newSize <= MAX_TABLE_SIZE && (newSize * maximumLoadFactor - liveEntries - nextChunkSize)
                    * REHASH_SLOTS_PER_ENTRY < alternateSize) {
                newSize *= 2;
            }
        }
        if (newSize <= 1 || newSize > MAX_TABLE_SIZE) {
            throw new UnsupportedOperationException("Hash table exceeds maximum size!");
        }
        return Math.toIntExact(newSize);
    }

    private void setupNewAlternate(final int oldTableSize) {
        for (int ii = 0; ii < mainKeySources.length; ++ii) {
            alternateKeySources[ii] = mainKeySources[ii];
            mainKeySources[ii] = InMemoryColumnSource.getImmutableMemoryColumnSource(tableSize,
                    alternateKeySources[ii].getType(), alternateKeySources[ii].getComponentType());
            mainKeySources[ii].ensureCapacity(tableSize);
        }
        alternateTableSize = oldTableSize;
        if (numEntries > 0) {
            rehashPointer = alternateTableSize;
        }

        alternateEntries = numEntries;
        numEntries = 0;
        alternateId = mainId;
        mainId = new ImmutableIntArraySource();
        mainId.ensureCapacity(tableSize);
    }

    /**
     * Drop the alternate table once every live entry has migrated to the main table.
     */
    protected void clearAlternate() {
        alternateEntries = 0;
        rehashPointer = 0;
        for (int ii = 0; ii < mainKeySources.length; ++ii) {
            alternateKeySources[ii] = null;
        }
        alternateId = null;
    }

    protected int hashToTableLocationAlternate(final int hash) {
        return hash & (alternateTableSize - 1);
    }

    /**
     * After creating the new alternate key sources, advise the derived classes, so they can cast them to the typed
     * versions of the column source.
     */
    protected abstract void adviseNewAlternate();

    protected abstract void migrateFront();

    /**
     * Migrate entries from the alternate table, examining {@link #REHASH_SLOTS_PER_ENTRY} alternate slots, whether they
     * hold a live entry, a tombstone or nothing, for each entry's worth of work requested.
     *
     * @param numEntriesToRehash the entries' worth of work to do, which pays for building as many entries
     * @return the entries' worth of work done: the slots examined divided by {@link #REHASH_SLOTS_PER_ENTRY}, or
     *         {@code numEntriesToRehash} if the alternate table was drained
     */
    protected abstract int rehashInternalPartial(int numEntriesToRehash);
}
