//
// Copyright (c) 2016-2026 Deephaven Data Labs and Patent Pending
//
package io.deephaven.engine.table.impl.join;

import io.deephaven.engine.table.ColumnSource;
import io.deephaven.engine.table.impl.by.typed.TypedHasherFactory;
import org.jetbrains.annotations.NotNull;

import static io.deephaven.engine.table.impl.JoinControl.MAX_TABLE_SIZE;

/**
 * A {@link KeyIdHasher} that only adds keys, for keys built once or only ever added to. The ids are handed out in
 * insertion order, and the table grows by a full rehash.
 * <p>
 * The typed implementations are generated by {@link TypedHasherFactory}; {@link #make} returns one suitable for the key
 * sources.
 */
public abstract class KeyIdHasherTypedBase extends KeyIdHasher {

    protected KeyIdHasherTypedBase(ColumnSource<?>[] tableKeySources, int tableSize, double maximumLoadFactor) {
        super(tableKeySources, tableSize, maximumLoadFactor);
    }

    /**
     * Make a hasher for keys with the types of {@code tableKeySources}.
     *
     * @param tableKeySources sources with the key types; every source later built or probed must have the same chunk
     *        types
     * @param tableSize the initial number of slots, a power of two
     * @param maximumLoadFactor the fraction of the slots that may be occupied before the table grows
     * @return a hasher with no keys
     */
    public static KeyIdHasherTypedBase make(
            @NotNull final ColumnSource<?>[] tableKeySources,
            final int tableSize,
            final double maximumLoadFactor) {
        return TypedHasherFactory.make(KeyIdHasherTypedBase.class, tableKeySources, tableKeySources, tableSize,
                maximumLoadFactor, maximumLoadFactor);
    }

    @Override
    public long size() {
        return numEntries;
    }

    @Override
    protected void prepareForChunk(final int nextChunkSize) {
        if (numEntries + nextChunkSize <= tableSize * maximumLoadFactor) {
            return;
        }
        long newSize = tableSize;
        while ((numEntries + nextChunkSize) > newSize * maximumLoadFactor) {
            newSize *= 2;
            if (newSize > MAX_TABLE_SIZE) {
                throw new UnsupportedOperationException("Hash table exceeds maximum size!");
            }
        }
        final int oldSize = tableSize;
        tableSize = (int) newSize;
        rehashInternalFull(oldSize);
    }

    @Override
    protected int allocateId(final int slot) {
        return nextId++;
    }
}
