plugins {
    id 'java-library'
    id 'io.deephaven.project.register'
}

description "Formula validation using lists of method patterns."

dependencies {
    implementation project(':Util')
    api project(':engine-validation')

    testImplementation project(":engine-test-utils")
    testImplementation project(":extensions-validation-base")

    testRuntimeOnly project(':log-to-slf4j')
    testRuntimeOnly project(':configs')
    testRuntimeOnly project(':test-configs')
    testRuntimeOnly libs.slf4j.simple
}
