plugins {
    id 'io.deephaven.project.register'
}

dependencies {
    implementation project(':plugin')
    implementation project(':server')
    implementation project(':engine-base')
    implementation project(':proto:proto-backplane-grpc')
    implementation project(':proto:proto-backplane-grpc-flight')

    compileOnly libs.autoservice
    compileOnly libs.jetbrains.annotations
    annotationProcessor libs.autoservice.compiler

    testImplementation libs.assertj
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testRuntimeOnly project(':log-to-slf4j')
}

test {
    useJUnitPlatform()
}
