io.deephaven.project.ProjectType=DOCKER_REGISTRY
# Keep this version in lockstep with the selenium version in gradle/libs.versions.toml
deephaven.registry.imageName=selenium/standalone-firefox:4.49.0
deephaven.registry.imageId=selenium/standalone-firefox@sha256:430b43aa2a573ad692fdde106e19330bdae68c8d5841615c45fd7627225d81d6
