io.deephaven.project.ProjectType=DOCKER_REGISTRY
# Even though the image is expected to be bumped from latest, we should correlate that with the specific version number
# for easier reference.
# 4.3.1
deephaven.registry.imageName=apache/kafka:latest
deephaven.registry.imageId=apache/kafka@sha256:77e3df9054047a88b520d0cc46e16696d3b22022e1d580aeccd2632df6532837
