package io.deephaven.server.table;

import io.deephaven.auth.Privilege;

public enum TableServicePrivilege implements Privilege {
    CAN_BATCH, CAN_GET_EXPORTED_TABLE_CREATION_RESPONSE, CAN_FETCH_TABLE, CAN_FETCH_PANDAS_TABLE, CAN_APPLY_PREVIEW_COLUMNS, CAN_CREATE_EMPTY_TABLE, CAN_CREATE_TIME_TABLE, CAN_DROP_COLUMNS, CAN_UPDATE, CAN_LAZY_UPDATE, CAN_VIEW, CAN_UPDATE_VIEW, CAN_SELECT, CAN_UPDATE_BY, CAN_SELECT_DISTINCT, CAN_FILTER_TABLE, CAN_CREATE_UNSTRUCTURED_FILTER, CAN_SORT, CAN_HEAD, CAN_TAIL, CAN_HEAD_BY, CAN_TAIL_BY, CAN_UNGROUP, CAN_MERGE_TABLES, CAN_CROSS_JOIN_TABLES, CAN_NATURAL_JOIN_TABLES, CAN_EXACT_JOIN_TABLES, CAN_LEFT_JOIN_TABLES, CAN_AS_OF_JOIN_TABLES, CAN_CREATE_COMBO_AGGREGATE, CAN_SNAPSHOT, CAN_FLATTEN, CAN_RUN_CHART_DOWNSAMPLE, CAN_CREATE_INPUT_TABLE, CAN_SUBSCRIBE_EXPORT_TABLE_UPDATES,
}
