"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright (c) 2016-2022 Deephaven Data Labs and Patent Pending
"""

from collections import abc as _abc
from deephaven_core.proto import ticket_pb2 as _ticket_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WrappedAuthenticationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """
    The type of the protobuf the auth payload protobuf.
    """
    payload: _builtins.bytes
    """
    The serialized payload of the protobuf instance.
    """
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WrappedAuthenticationRequest: _TypeAlias = WrappedAuthenticationRequest  # noqa: Y015

@_typing.final
class HandshakeRequest(_message.Message):
    """
    The request that a client provides to a server on handshake.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_PROTOCOL_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def auth_protocol(self) -> _builtins.int:
        """
        A defined protocol version.

        Deephaven's OSS protocols are as follows:
        - protocol = 0: most recent HandshakeResponse payload
        - protocol = 1: payload is BasicAuth
        """

    @auth_protocol.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def auth_protocol(self, value: _builtins.int) -> None:
        """
        A defined protocol version.

        Deephaven's OSS protocols are as follows:
        - protocol = 0: most recent HandshakeResponse payload
        - protocol = 1: payload is BasicAuth
        """

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def payload(self) -> _builtins.bytes:
        """
        Arbitrary auth/handshake info.
        """

    @payload.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def payload(self, value: _builtins.bytes) -> None:
        """
        Arbitrary auth/handshake info.
        """

    def __init__(
        self,
        *,
        auth_protocol: _builtins.int = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_protocol", b"auth_protocol", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HandshakeRequest: _TypeAlias = HandshakeRequest  # noqa: Y015

@_typing.final
class HandshakeResponse(_message.Message):
    """
    Servers respond with information needed to make subsequent requests tied to this session.
    The session token should be refreshed prior to the deadline, which is represented as milliseconds since the
    epoch. Clients are encouraged to use the expiration delay and cookie deadline to determine a good time to refresh.
    """

    DESCRIPTOR: _descriptor.Descriptor

    METADATA_HEADER_FIELD_NUMBER: _builtins.int
    SESSION_TOKEN_FIELD_NUMBER: _builtins.int
    TOKEN_DEADLINE_TIME_MILLIS_FIELD_NUMBER: _builtins.int
    TOKEN_EXPIRATION_DELAY_MILLIS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def metadata_header(self) -> _builtins.bytes:
        """
        The metadata header to identify the session. This value is static and defined via configuration.
        """

    @metadata_header.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def metadata_header(self, value: _builtins.bytes) -> None:
        """
        The metadata header to identify the session. This value is static and defined via configuration.
        """

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def session_token(self) -> _builtins.bytes:
        """
        Arbitrary session_token to assign to the value to the provided metadata header.
        """

    @session_token.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def session_token(self, value: _builtins.bytes) -> None:
        """
        Arbitrary session_token to assign to the value to the provided metadata header.
        """

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def token_deadline_time_millis(self) -> _builtins.int:
        """
        When this session_token will be considered invalid by the server.
        """

    @token_deadline_time_millis.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def token_deadline_time_millis(self, value: _builtins.int) -> None:
        """
        When this session_token will be considered invalid by the server.
        """

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def token_expiration_delay_millis(self) -> _builtins.int:
        """
        The length of time that this token was intended to live. Note that `refreshSessionToken` may return the
        existing token to reduce overhead and to prevent denial-of-service caused by refreshing too frequently.
        """

    @token_expiration_delay_millis.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def token_expiration_delay_millis(self, value: _builtins.int) -> None:
        """
        The length of time that this token was intended to live. Note that `refreshSessionToken` may return the
        existing token to reduce overhead and to prevent denial-of-service caused by refreshing too frequently.
        """

    def __init__(
        self,
        *,
        metadata_header: _builtins.bytes = ...,
        session_token: _builtins.bytes = ...,
        token_deadline_time_millis: _builtins.int = ...,
        token_expiration_delay_millis: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata_header", b"metadata_header", "session_token", b"session_token", "token_deadline_time_millis", b"token_deadline_time_millis", "token_expiration_delay_millis", b"token_expiration_delay_millis"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HandshakeResponse: _TypeAlias = HandshakeResponse  # noqa: Y015

@_typing.final
class CloseSessionResponse(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CloseSessionResponse: _TypeAlias = CloseSessionResponse  # noqa: Y015

@_typing.final
class ReleaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def id(self) -> _ticket_pb2.Ticket: ...
    def __init__(
        self,
        *,
        id: _ticket_pb2.Ticket | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseRequest: _TypeAlias = ReleaseRequest  # noqa: Y015

@_typing.final
class ReleaseResponse(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseResponse: _TypeAlias = ReleaseResponse  # noqa: Y015

@_typing.final
class ExportRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: _builtins.int
    RESULT_ID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def source_id(self) -> _ticket_pb2.Ticket: ...
    @_builtins.property
    def result_id(self) -> _ticket_pb2.Ticket: ...
    def __init__(
        self,
        *,
        source_id: _ticket_pb2.Ticket | None = ...,
        result_id: _ticket_pb2.Ticket | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result_id", b"result_id", "source_id", b"source_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result_id", b"result_id", "source_id", b"source_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportRequest: _TypeAlias = ExportRequest  # noqa: Y015

@_typing.final
class ExportResponse(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportResponse: _TypeAlias = ExportResponse  # noqa: Y015

@_typing.final
class PublishRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: _builtins.int
    RESULT_ID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def source_id(self) -> _ticket_pb2.Ticket: ...
    @_builtins.property
    def result_id(self) -> _ticket_pb2.Ticket: ...
    def __init__(
        self,
        *,
        source_id: _ticket_pb2.Ticket | None = ...,
        result_id: _ticket_pb2.Ticket | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result_id", b"result_id", "source_id", b"source_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result_id", b"result_id", "source_id", b"source_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PublishRequest: _TypeAlias = PublishRequest  # noqa: Y015

@_typing.final
class PublishResponse(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PublishResponse: _TypeAlias = PublishResponse  # noqa: Y015

@_typing.final
class ExportNotificationRequest(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportNotificationRequest: _TypeAlias = ExportNotificationRequest  # noqa: Y015

@_typing.final
class ExportNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ExportNotification._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ExportNotification._State.ValueType  # 0
        """This item is a dependency, but hasn't been registered yet."""
        PENDING: ExportNotification._State.ValueType  # 1
        """This item has pending dependencies."""
        PUBLISHING: ExportNotification._State.ValueType  # 2
        """This item is a client-supplied dependency with no guarantee on timing to EXPORT state."""
        QUEUED: ExportNotification._State.ValueType  # 3
        """This item is eligible for resolution and has been submitted to the executor."""
        RUNNING: ExportNotification._State.ValueType  # 4
        """This item is now executing."""
        EXPORTED: ExportNotification._State.ValueType  # 5
        """This item was successfully exported and is currently being retained."""
        RELEASED: ExportNotification._State.ValueType  # 6
        """This item was successfully released."""
        CANCELLED: ExportNotification._State.ValueType  # 7
        """ CANCELLED: The user cancelled the item before it exported."""
        FAILED: ExportNotification._State.ValueType  # 8
        """This item had a specific error."""
        DEPENDENCY_FAILED: ExportNotification._State.ValueType  # 9
        """One of this item's dependencies had an internal error before it exported."""
        DEPENDENCY_NEVER_FOUND: ExportNotification._State.ValueType  # 10
        """One of this item's dependencies was already released or never submitted within the out-of-order window."""
        DEPENDENCY_CANCELLED: ExportNotification._State.ValueType  # 11
        """Dependency was cancelled, causing a cascading cancel that applies to this export."""
        DEPENDENCY_RELEASED: ExportNotification._State.ValueType  # 12
        """Dependency was already released, causing a cascading failure that applies to this export."""

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    UNKNOWN: ExportNotification.State.ValueType  # 0
    """This item is a dependency, but hasn't been registered yet."""
    PENDING: ExportNotification.State.ValueType  # 1
    """This item has pending dependencies."""
    PUBLISHING: ExportNotification.State.ValueType  # 2
    """This item is a client-supplied dependency with no guarantee on timing to EXPORT state."""
    QUEUED: ExportNotification.State.ValueType  # 3
    """This item is eligible for resolution and has been submitted to the executor."""
    RUNNING: ExportNotification.State.ValueType  # 4
    """This item is now executing."""
    EXPORTED: ExportNotification.State.ValueType  # 5
    """This item was successfully exported and is currently being retained."""
    RELEASED: ExportNotification.State.ValueType  # 6
    """This item was successfully released."""
    CANCELLED: ExportNotification.State.ValueType  # 7
    """ CANCELLED: The user cancelled the item before it exported."""
    FAILED: ExportNotification.State.ValueType  # 8
    """This item had a specific error."""
    DEPENDENCY_FAILED: ExportNotification.State.ValueType  # 9
    """One of this item's dependencies had an internal error before it exported."""
    DEPENDENCY_NEVER_FOUND: ExportNotification.State.ValueType  # 10
    """One of this item's dependencies was already released or never submitted within the out-of-order window."""
    DEPENDENCY_CANCELLED: ExportNotification.State.ValueType  # 11
    """Dependency was cancelled, causing a cascading cancel that applies to this export."""
    DEPENDENCY_RELEASED: ExportNotification.State.ValueType  # 12
    """Dependency was already released, causing a cascading failure that applies to this export."""

    TICKET_FIELD_NUMBER: _builtins.int
    EXPORT_STATE_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    DEPENDENT_HANDLE_FIELD_NUMBER: _builtins.int
    export_state: Global___ExportNotification.State.ValueType
    context: _builtins.str
    """
    any errors will include an id that can be used to find details of the error in the logs
    """
    dependent_handle: _builtins.str
    """
    will be set to an identifier of the dependency that cascaded the error if applicable
    """
    @_builtins.property
    def ticket(self) -> _ticket_pb2.Ticket: ...
    def __init__(
        self,
        *,
        ticket: _ticket_pb2.Ticket | None = ...,
        export_state: Global___ExportNotification.State.ValueType = ...,
        context: _builtins.str = ...,
        dependent_handle: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ticket", b"ticket"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "dependent_handle", b"dependent_handle", "export_state", b"export_state", "ticket", b"ticket"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExportNotification: _TypeAlias = ExportNotification  # noqa: Y015

@_typing.final
class TerminationNotificationRequest(_message.Message):
    """Intentionally empty and is here for backwards compatibility should this API change."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TerminationNotificationRequest: _TypeAlias = TerminationNotificationRequest  # noqa: Y015

@_typing.final
class TerminationNotificationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StackTrace(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        MESSAGE_FIELD_NUMBER: _builtins.int
        ELEMENTS_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        message: _builtins.str
        @_builtins.property
        def elements(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            type: _builtins.str = ...,
            message: _builtins.str = ...,
            elements: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["elements", b"elements", "message", b"message", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ABNORMAL_TERMINATION_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    IS_FROM_UNCAUGHT_EXCEPTION_FIELD_NUMBER: _builtins.int
    STACK_TRACES_FIELD_NUMBER: _builtins.int
    abnormal_termination: _builtins.bool
    """whether or not this termination is expected"""
    reason: _builtins.str
    """if additional information is available then provide it in this field"""
    is_from_uncaught_exception: _builtins.bool
    """if this is due to an exception, whether or not it was uncaught"""
    @_builtins.property
    def stack_traces(self) -> _containers.RepeatedCompositeFieldContainer[Global___TerminationNotificationResponse.StackTrace]:
        """if applicable, the list of stack traces in reverse causal order"""

    def __init__(
        self,
        *,
        abnormal_termination: _builtins.bool = ...,
        reason: _builtins.str = ...,
        is_from_uncaught_exception: _builtins.bool = ...,
        stack_traces: _abc.Iterable[Global___TerminationNotificationResponse.StackTrace] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abnormal_termination", b"abnormal_termination", "is_from_uncaught_exception", b"is_from_uncaught_exception", "reason", b"reason", "stack_traces", b"stack_traces"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TerminationNotificationResponse: _TypeAlias = TerminationNotificationResponse  # noqa: Y015
