io.deephaven.project.ProjectType=DOCKER_REGISTRY
# Even though the image is expected to be bumped from latest, we should correlate that with the specific version number
# for easier reference.
# 4.3.1
deephaven.registry.imageName=apache/kafka-native:latest
deephaven.registry.imageId=apache/kafka-native@sha256:2885898ba17065023f1bd605f3a81efcfa986014f062b73b91ef5462485f9060
