io.deephaven.project.ProjectType=DOCKER_REGISTRY
deephaven.registry.imageName=ghcr.io/deephaven/cpp-clients-multi-base:latest
# When the image version changes, remember to update cpp-client/build-dependencies.sh to match the image's content
deephaven.registry.imageId=ghcr.io/deephaven/cpp-clients-multi-base@sha256:c5ad1ad7221983bd27b7ac65acfd1321d34b00c7b2a9c957a83d668729d2ee56
deephaven.registry.platform=linux/amd64
