
<!--
  ~ Copyright (c) 2016-2021 Deephaven Data Labs and Patent Pending
  -->

<Theme>
    <Name>Test</Name>
    <Text>
        <FigureTextFont>
            <Name>SanSerif</Name>
            <Style>PLAIN</Style>
            <Size>14</Size>
            <Color r="65" g="65" b="65"/>
        </FigureTextFont>
        <FigureTitleFont>
            <Name>Arial</Name>
            <Style>BOLD</Style>
            <Size>28</Size>
            <Color r="0" g="0" b="0"/>
        </FigureTitleFont>
        <ChartTitleFont>
            <Name>SanSerif</Name>
            <Style>BOLD</Style>
            <Size>20</Size>
            <Color r="255" g="0" b="0"/>
        </ChartTitleFont>
        <AxisTitleFont>
            <Name>SanSerif</Name>
            <Style>PLAIN</Style>
            <Size>14</Size>
            <Color r="0" g="255" b="0"/>
        </AxisTitleFont>
        <TickValuesFont>
            <Name>Helvetica</Name>
            <Style>PLAIN</Style>
            <Size>10</Size>
            <Color r="0" g="0" b="255"/>
        </TickValuesFont>
        <LegendFont>
            <Name>SanSerif</Name>
            <Style>PLAIN</Style>
            <Size>10</Size>
            <Color r="255" g="255" b="255"/>
        </LegendFont>
    </Text>
    <PlotElements>
        <Background>
            <Color r="216" g="216" b="216"/>
        </Background>
        <Grid>
            <Visibility x="false"/>
            <Color r="175" g="175" b="175"/>
        </Grid>
        <Axis>
            <Color r="65" g="65" b="65"/>
        </Axis>
        <Series>
            <ColorPaletteArray>matplotlib</ColorPaletteArray>
        </Series>
    </PlotElements>
</Theme>