//
// Copyright (c) 2016-2026 Deephaven Data Labs and Patent Pending
//
package io.deephaven.engine.table.impl.select;

import io.deephaven.base.MathUtil;
import io.deephaven.base.verify.Assert;
import io.deephaven.base.verify.Require;
import io.deephaven.chunk.Chunk;
import io.deephaven.chunk.LongChunk;
import io.deephaven.chunk.WritableLongChunk;
import io.deephaven.chunk.attributes.Values;
import io.deephaven.engine.primitive.iterator.CloseableIterator;
import io.deephaven.engine.rowset.RowSequence;
import io.deephaven.engine.rowset.RowSet;
import io.deephaven.engine.rowset.RowSetBuilderSequential;
import io.deephaven.engine.rowset.RowSetFactory;
import io.deephaven.engine.rowset.chunkattributes.OrderedRowKeys;
import io.deephaven.engine.table.ColumnSource;
import io.deephaven.engine.table.WritableColumnSource;
import io.deephaven.engine.table.impl.TupleSourceFactory;
import io.deephaven.engine.table.impl.by.typed.TypedHasherFactory;
import io.deephaven.engine.table.impl.sources.InMemoryColumnSource;
import io.deephaven.engine.table.impl.sources.immutable.ImmutableLongArraySource;
import io.deephaven.engine.table.impl.util.TypedHasherUtil.BuildOrProbeContext.BuildContext;
import io.deephaven.engine.table.impl.util.TypedHasherUtil.BuildOrProbeContext.ProbeContext;
import io.deephaven.engine.table.iterators.ChunkedColumnIterator;
import io.deephaven.util.QueryConstants;
import io.deephaven.util.SafeCloseable;
import io.deephaven.util.mutable.MutableInt;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;

import static io.deephaven.engine.table.impl.util.TypedHasherUtil.getKeyChunks;
import static io.deephaven.engine.table.impl.util.TypedHasherUtil.getPrevKeyChunks;

/**
 * A {@link SetKernel} holding the keys in an open addressed hash table whose typed subclasses are generated by
 * {@link TypedHasherFactory}, so that a filter can look up a chunk of keys per column without first assembling a tuple
 * per row.
 * <p>
 * Each slot holds a key and the number of set rows holding it. A key whose count falls to zero stays in its slot until
 * {@link #finishRemove(RowSequence)}, and is then replaced by a tombstone. A tombstone keeps probes for other keys
 * going past it, is reused by a later insertion, and is dropped when the table is rehashed. The table is sized from the
 * keys in the set, so it does not grow with the keys the set has held and lost.
 */
public abstract class DistinctKeySet extends SetKernel {

    private static final int CHUNK_SIZE = 1 << 12;
    private static final int MINIMUM_INITIAL_TABLE_SIZE = CHUNK_SIZE;
    private static final long MAX_TABLE_SIZE = 1 << 30;
    private static final double MAXIMUM_LOAD_FACTOR = 0.75;
    private static final double TARGET_LOAD_FACTOR = 0.70;

    /**
     * The alternate slots a partial rehash examines for each entry about to be built. The maximum load factor must
     * exceed its reciprocal, so that the alternate table drains before the new table fills.
     */
    public static final int REHASH_SLOTS_PER_ENTRY = 3;

    /** The state of a slot that has never held a key. */
    protected static final long EMPTY_STATE = QueryConstants.NULL_LONG;
    /** The state of a slot whose key has left the set. */
    protected static final long TOMBSTONE_STATE = -1;

    /** The number of slots in the main table. */
    protected int tableSize;
    /**
     * The number of slots in the alternate table; "1" to start with is a lie, but rehashPointer is zero, so a location
     * in it is positive and can be compared against rehashPointer safely.
     */
    protected int alternateTableSize = 1;
    /** The alternate slots below this one have yet to migrate to the main table. */
    protected int rehashPointer = 0;

    /** The occupied slots of the main table, including tombstones. */
    protected long numEntries = 0;
    /** The keys in both tables, including those whose count has fallen to zero during this update. */
    protected long liveEntries = 0;
    /** The occupied slots of the alternate table, including tombstones. */
    protected long alternateEntries = 0;

    private final double maximumLoadFactor;
    private boolean fullRehash = true;

    /** The set table's key sources, reinterpreted to primitives. */
    private final ColumnSource<?>[] keySources;
    protected final WritableColumnSource[] mainKeySources;
    protected final WritableColumnSource[] alternateKeySources;

    /** The set rows holding each main slot's key, or {@link #EMPTY_STATE} or {@link #TOMBSTONE_STATE}. */
    protected ImmutableLongArraySource mainCount = new ImmutableLongArraySource();
    /** The set rows holding each alternate slot's key, as for {@link #mainCount}. */
    protected ImmutableLongArraySource alternateCount;

    /** The keys inserted during this update, which were not in the set before it. */
    protected long insertedKeys;
    /** The keys whose count fell to zero during this update. */
    protected long emptiedKeys;
    /** The keys whose count rose from zero during this update, having fallen to zero earlier in it. */
    protected long revivedKeys;

    /**
     * Create a set from the keys of {@code initialRows}, which may hold the same key more than once.
     *
     * @param keySources The set table's key sources, reinterpreted to primitives
     * @param initialRows The rows holding the initial keys
     * @param usePrev Whether to read the previous values of {@code initialRows}
     * @return The new set
     */
    static DistinctKeySet create(
            @NotNull final ColumnSource<?>[] keySources,
            @NotNull final RowSet initialRows,
            final boolean usePrev) {
        final DistinctKeySet keySet = TypedHasherFactory.make(DistinctKeySet.class, keySources, keySources,
                MINIMUM_INITIAL_TABLE_SIZE, MAXIMUM_LOAD_FACTOR, TARGET_LOAD_FACTOR);
        keySet.add(initialRows, usePrev
                ? Arrays.stream(keySources).map(ColumnSource::getPrevSource).toArray(ColumnSource[]::new)
                : keySources);
        // Rehash incrementally from now on, a little with each update, rather than all at once when the table must
        // grow.
        keySet.fullRehash = false;
        return keySet;
    }

    protected DistinctKeySet(
            @NotNull final ColumnSource<?>[] tableKeySources,
            final int tableSize,
            final double maximumLoadFactor) {
        this.tableSize = tableSize;
        Require.leq(tableSize, "tableSize", MAX_TABLE_SIZE);
        Require.gtZero(tableSize, "tableSize");
        Require.eq(Integer.bitCount(tableSize), "Integer.bitCount(tableSize)", 1);
        Require.inRange(maximumLoadFactor, 0.0, 0.95, "maximumLoadFactor");
        Require.gt(maximumLoadFactor, "maximumLoadFactor", 1.0 / REHASH_SLOTS_PER_ENTRY,
                "1.0 / REHASH_SLOTS_PER_ENTRY");
        this.maximumLoadFactor = maximumLoadFactor;

        keySources = tableKeySources;
        mainKeySources = new WritableColumnSource[tableKeySources.length];
        alternateKeySources = new WritableColumnSource[tableKeySources.length];
        for (int ii = 0; ii < tableKeySources.length; ++ii) {
            mainKeySources[ii] = InMemoryColumnSource.getImmutableMemoryColumnSource(tableSize,
                    tableKeySources[ii].getType(), tableKeySources[ii].getComponentType());
        }
        mainCount.ensureCapacity(tableSize);
    }

    /**
     * Increment the count of each key in {@code sourceKeyChunks}, inserting the keys not in the set.
     */
    protected abstract void addKeys(RowSequence rowSequence, Chunk[] sourceKeyChunks);

    /**
     * Decrement the count of each key in {@code sourceKeyChunks}, each of which must be in the set.
     */
    protected abstract void removeKeys(RowSequence rowSequence, Chunk[] sourceKeyChunks);

    /**
     * Replace with a tombstone each key in {@code sourceKeyChunks} whose count is zero.
     */
    protected abstract void tombstoneEmptied(RowSequence rowSequence, Chunk[] sourceKeyChunks);

    /**
     * Select the row keys whose key is in the set, or, if {@code inclusion} is false, not in the set.
     */
    protected abstract void match(RowSequence rowSequence, Chunk[] sourceKeyChunks,
            LongChunk<OrderedRowKeys> rowKeys, WritableLongChunk<OrderedRowKeys> results, boolean inclusion);

    protected abstract void rehashInternalFull(int oldSize);

    /**
     * Migrate entries from the alternate table, examining {@link #REHASH_SLOTS_PER_ENTRY} alternate slots, whether they
     * hold a live entry, a tombstone or nothing, for each entry's worth of work requested.
     *
     * @param numEntriesToRehash the entries' worth of work to do, which pays for building as many entries
     * @return the entries' worth of work done: the slots examined divided by {@link #REHASH_SLOTS_PER_ENTRY}, or
     *         {@code numEntriesToRehash} if the alternate table was drained
     */
    protected abstract int rehashInternalPartial(int numEntriesToRehash);

    protected abstract void migrateFront();

    /**
     * After creating the new alternate key sources, advise the derived classes, so they can cast them to the typed
     * versions of the column source and adjust the derived class pointers.
     */
    protected abstract void adviseNewAlternate();

    protected int hashToTableLocation(final int hash) {
        return hash & (tableSize - 1);
    }

    protected int hashToTableLocationAlternate(final int hash) {
        return hash & (alternateTableSize - 1);
    }

    @Override
    final long size() {
        return liveEntries;
    }

    @Override
    final void beginUpdate() {
        insertedKeys = 0;
        emptiedKeys = 0;
        revivedKeys = 0;
        // Do some rehash work on every update, so that the alternate table is eventually dropped.
        if (rehashPointer > 0) {
            rehashInternalPartial(CHUNK_SIZE);
            if (rehashPointer == 0) {
                clearAlternate();
            }
        }
    }

    @Override
    final void finishRemove(@NotNull final RowSequence removedRows) {
        if (emptiedKeys == revivedKeys) {
            // Every key that fell to zero was revived, so none is left to replace.
            return;
        }
        probeTable(removedRows, this::tombstoneEmptied);
    }

    @Override
    final boolean keysAdded() {
        return insertedKeys > 0;
    }

    @Override
    final boolean keysRemoved() {
        return emptiedKeys > revivedKeys;
    }

    @Override
    final void add(@NotNull final RowSequence rows) {
        add(rows, keySources);
    }

    private void add(@NotNull final RowSequence rows, @NotNull final ColumnSource<?>[] sources) {
        if (rows.isEmpty()) {
            return;
        }
        // @formatter:off
        try (final BuildContext bc = new BuildContext(sources, (int) Math.min(rows.size(), CHUNK_SIZE));
             final RowSequence.Iterator rowsIterator = rows.getRowSequenceIterator()) {
            // @formatter:on
            // noinspection unchecked
            final Chunk<Values>[] sourceKeyChunks = new Chunk[sources.length];
            final MutableInt rehashCredits = new MutableInt(0);
            while (rowsIterator.hasMore()) {
                final RowSequence chunkRows = rowsIterator.getNextRowSequenceWithLength(bc.chunkSize);
                final int nextChunkSize = chunkRows.intSize();
                while (doRehash(rehashCredits, nextChunkSize)) {
                    migrateFront();
                }
                getKeyChunks(sources, bc.getContexts, sourceKeyChunks, chunkRows);
                final long oldEntries = numEntries;
                addKeys(chunkRows, sourceKeyChunks);
                // Building into fresh slots spends the credit that rehashing has built up; finding existing keys, or
                // reusing tombstones, does not.
                rehashCredits.subtract(Math.toIntExact(numEntries - oldEntries));
                bc.resetSharedContexts();
            }
        }
    }

    @Override
    final void remove(@NotNull final RowSequence rows) {
        probeTable(rows, this::removeKeys);
    }

    @FunctionalInterface
    private interface ProbeHandler {
        void doProbe(RowSequence chunkRows, Chunk[] sourceKeyChunks);
    }

    private void probeTable(@NotNull final RowSequence rows, @NotNull final ProbeHandler handler) {
        if (rows.isEmpty()) {
            return;
        }
        // @formatter:off
        try (final ProbeContext pc = new ProbeContext(keySources, (int) Math.min(rows.size(), CHUNK_SIZE));
             final RowSequence.Iterator rowsIterator = rows.getRowSequenceIterator()) {
            // @formatter:on
            // noinspection unchecked
            final Chunk<Values>[] sourceKeyChunks = new Chunk[keySources.length];
            while (rowsIterator.hasMore()) {
                final RowSequence chunkRows = rowsIterator.getNextRowSequenceWithLength(pc.chunkSize);
                getPrevKeyChunks(keySources, pc.getContexts, sourceKeyChunks, chunkRows);
                handler.doProbe(chunkRows, sourceKeyChunks);
                pc.resetSharedContexts();
            }
        }
    }

    @Override
    final void matchValues(
            @NotNull final MatchContext context,
            @NotNull final Chunk<Values>[] keyChunks,
            @NotNull final LongChunk<OrderedRowKeys> rowKeys,
            @NotNull final WritableLongChunk<OrderedRowKeys> results,
            final boolean inclusion) {
        results.setSize(0);
        match(null, keyChunks, rowKeys, results, inclusion);
    }

    @Override
    final CloseableIterator<Object> iterator() {
        final CloseableIterator<Object> mainKeys = slotKeys(mainKeySources, mainCount, tableSize);
        final int alternateSlots = rehashPointer;
        if (alternateSlots == 0) {
            return mainKeys;
        }
        // noinspection unchecked
        return CloseableIterator.concat(mainKeys, slotKeys(alternateKeySources, alternateCount, alternateSlots));
    }

    private static CloseableIterator<Object> slotKeys(
            @NotNull final WritableColumnSource<?>[] slotKeySources,
            @NotNull final ImmutableLongArraySource slotCounts,
            final int slotCount) {
        final RowSetBuilderSequential builder = RowSetFactory.builderSequential();
        for (int slot = 0; slot < slotCount; ++slot) {
            if (slotCounts.getUnsafe(slot) > 0) {
                builder.appendKey(slot);
            }
        }
        final RowSet liveSlots = builder.build();
        if (liveSlots.isEmpty()) {
            liveSlots.close();
            return CloseableIterator.empty();
        }
        // noinspection unchecked
        final CloseableIterator<Object> keys = (CloseableIterator<Object>) ChunkedColumnIterator.make(
                TupleSourceFactory.makeTupleSource(slotKeySources), liveSlots,
                (int) Math.min(liveSlots.size(), CHUNK_SIZE));
        return new CloseableIterator<>() {
            @Override
            public boolean hasNext() {
                return keys.hasNext();
            }

            @Override
            public Object next() {
                return keys.next();
            }

            @Override
            public void close() {
                try (final SafeCloseable ignored = liveSlots) {
                    keys.close();
                }
            }
        };
    }

    /**
     * @param rehashCredits the rehash work this operation has done, in entries' worth of alternate slots examined
     *        ({@link #REHASH_SLOTS_PER_ENTRY} slots each), which pays for building as many entries (input/output)
     * @param nextChunkSize the size of the chunk we are processing
     * @return true if a front migration is required
     */
    private boolean doRehash(final MutableInt rehashCredits, final int nextChunkSize) {
        if (rehashPointer > 0) {
            final int requiredRehash = nextChunkSize - rehashCredits.get();
            if (requiredRehash <= 0) {
                return false;
            }

            // before building, we need to do at least as much rehash work as we would do build work
            rehashCredits.add(rehashInternalPartial(requiredRehash));
            if (rehashPointer == 0) {
                clearAlternate();
            }
        }

        if (!rehashRequired(nextChunkSize)) {
            return false;
        }

        final int oldTableSize = tableSize;
        tableSize = computeTableSize(nextChunkSize, oldTableSize);

        // we can't give the caller credit for rehashes with the old table, we need to begin migrating things again
        if (rehashCredits.get() > 0) {
            rehashCredits.set(0);
        }

        if (fullRehash) {
            // the initial build has never removed a key, so there is neither an alternate nor a tombstone to drop
            Assert.eqZero(rehashPointer, "rehashPointer");
            rehashInternalFull(oldTableSize);
            return false;
        }
        Assert.eqZero(rehashPointer, "rehashPointer");

        setupNewAlternate(oldTableSize);
        adviseNewAlternate();
        if (liveEntries == 0) {
            // every entry is a tombstone, so nothing needs to migrate; drop the old table rather than examine it
            clearAlternate();
            return false;
        }

        return true;
    }

    private boolean rehashRequired(final int nextChunkSize) {
        return (numEntries + nextChunkSize) > (tableSize * maximumLoadFactor);
    }

    /**
     * @param nextChunkSize the size of the chunk about to be built
     * @param alternateSize the size of the table that becomes the alternate
     * @return the size of the new table
     */
    private int computeTableSize(final int nextChunkSize, final int alternateSize) {
        // we use the number of liveEntries multiplied by 2, so that as we rehash we can both consume a slot for the
        // live entry from the alternate table; and also consume a slot for the new value.
        final long desiredEntries = Math.max(liveEntries * 2, liveEntries + nextChunkSize);
        long newTableSize =
                MathUtil.roundUpPowerOf2(Math.max(tableSize, (long) (desiredEntries / maximumLoadFactor)));
        // Each build examines REHASH_SLOTS_PER_ENTRY alternate slots per entry before inserting, so the alternate
        // drains before the new table needs another rehash if the entries that fit under the load factor pay for
        // examining every alternate slot. An alternate with no live entries is dropped without being examined.
        if (!fullRehash && liveEntries > 0) {
            while (newTableSize <= MAX_TABLE_SIZE && (newTableSize * maximumLoadFactor - liveEntries - nextChunkSize)
                    * REHASH_SLOTS_PER_ENTRY < alternateSize) {
                newTableSize *= 2;
            }
        }
        if (newTableSize <= 1 || newTableSize > MAX_TABLE_SIZE) {
            throw new UnsupportedOperationException("Hash table exceeds maximum size!");
        }
        return Math.toIntExact(newTableSize);
    }

    private void setupNewAlternate(final int oldTableSize) {
        Assert.eqZero(rehashPointer, "rehashPointer");

        for (int ii = 0; ii < mainKeySources.length; ++ii) {
            alternateKeySources[ii] = mainKeySources[ii];
            mainKeySources[ii] = InMemoryColumnSource.getImmutableMemoryColumnSource(tableSize,
                    alternateKeySources[ii].getType(), alternateKeySources[ii].getComponentType());
            mainKeySources[ii].ensureCapacity(tableSize);
        }
        alternateTableSize = oldTableSize;
        if (numEntries > 0) {
            rehashPointer = alternateTableSize;
        }

        alternateEntries = numEntries;
        numEntries = 0;
        alternateCount = mainCount;
        mainCount = new ImmutableLongArraySource();
        mainCount.ensureCapacity(tableSize);
    }

    /**
     * Drop the alternate table once every live entry has migrated to the main table.
     */
    protected void clearAlternate() {
        alternateEntries = 0;
        rehashPointer = 0;
        for (int ii = 0; ii < mainKeySources.length; ++ii) {
            alternateKeySources[ii] = null;
        }
        alternateCount = null;
    }
}
