//
// Copyright (c) 2016-2026 Deephaven Data Labs and Patent Pending
//
package io.deephaven.engine.table.impl.select;

import io.deephaven.base.verify.Assert;
import io.deephaven.chunk.Chunk;
import io.deephaven.chunk.ObjectChunk;
import io.deephaven.chunk.WritableChunk;
import io.deephaven.chunk.attributes.Values;
import io.deephaven.engine.rowset.RowSequence;
import io.deephaven.engine.table.ColumnSource;
import io.deephaven.engine.table.TupleSource;
import io.deephaven.engine.table.impl.TupleSourceFactory;
import it.unimi.dsi.fastutil.Hash;
import it.unimi.dsi.fastutil.objects.Object2LongOpenCustomHashMap;
import it.unimi.dsi.fastutil.objects.ObjectIterator;
import org.jetbrains.annotations.NotNull;

import java.util.function.Consumer;

/**
 * A {@link SetKernel} for a compound key, held as the tuples a {@link TupleSource} over the set's key sources makes, in
 * a fastutil open hash map from tuple to count.
 * <p>
 * A subclass for the key's column types, generated by {@link TupleSetKernelFactory}, matches a chunk of keys by setting
 * the fields of one reusable probe from the key chunks for each row, so that no tuple is assembled per row; its
 * {@link Hash.Strategy} hashes and compares a probe and a stored tuple alike, by each column's {@code Comparisons}.
 * Adding and removing set rows does assemble their tuples, which become the stored keys.
 */
public abstract class TupleMapSetKernel extends SetKernel {

    private static final int CHUNK_SIZE = 1 << 12;

    private final TupleSource<?> tupleSource;
    /**
     * The number of set rows holding each key. Must be a fastutil open hash map: see {@link SharedSetKernel#kernel()}
     * for the behavior we rely on when it is concurrently modified.
     */
    private final Object2LongOpenCustomHashMap<Object> counts;

    /** The keys inserted during this update, which were not in the set before it. */
    private long insertedKeys;
    /** The keys whose count fell to zero during this update. */
    private long emptiedKeys;
    /** The keys whose count rose from zero during this update, having fallen to zero earlier in it. */
    private long revivedKeys;

    /**
     * @param keySources The set table's key sources, reinterpreted to primitives
     * @param strategy Hashes and compares the tuples {@code keySources} make, and the subclass's probes
     */
    protected TupleMapSetKernel(
            @NotNull final ColumnSource<?>[] keySources,
            @NotNull final Hash.Strategy<Object> strategy) {
        tupleSource = TupleSourceFactory.makeTupleSource(keySources);
        counts = new Object2LongOpenCustomHashMap<>(strategy);
    }

    /**
     * @param probe A probe whose fields hold a key
     * @return Whether the key is in the set
     */
    protected final boolean contains(@NotNull final Object probe) {
        return counts.containsKey(probe);
    }

    final void add(@NotNull final RowSequence rows, final boolean usePrev) {
        forEachTupleChunk(rows, usePrev, this::addTuples);
    }

    @Override
    final long size() {
        return counts.size();
    }

    @Override
    final void beginUpdate() {
        insertedKeys = 0;
        emptiedKeys = 0;
        revivedKeys = 0;
    }

    @Override
    final void add(@NotNull final RowSequence rows) {
        add(rows, false);
    }

    @Override
    final void remove(@NotNull final RowSequence rows) {
        forEachTupleChunk(rows, true, this::removeTuples);
    }

    @Override
    final void finishRemove(@NotNull final RowSequence removedRows) {
        if (emptiedKeys == revivedKeys) {
            // Every key that fell to zero was revived, so none is left to drop.
            return;
        }
        forEachTupleChunk(removedRows, true, this::dropEmptied);
    }

    @Override
    final boolean keysAdded() {
        return insertedKeys > 0;
    }

    @Override
    final boolean keysRemoved() {
        return emptiedKeys > revivedKeys;
    }

    /**
     * Copy the columns {@code columns} of the next tuples of {@code tuples}, keys in the set, into {@code keyChunks},
     * as many as fit: column {@code columns[ii]} into chunk {@code ii}. Sets every chunk's size to the number copied.
     *
     * @return Whether any tuple was copied
     */
    protected abstract boolean exportTuples(
            @NotNull ObjectIterator<Object> tuples,
            int @NotNull [] columns,
            @NotNull WritableChunk<Values>[] keyChunks);

    private static final class TupleExportContext extends ExportContext {
        private final ObjectIterator<Object> tuples;
        private final int[] columns;

        private TupleExportContext(@NotNull final ObjectIterator<Object> tuples, final int @NotNull [] columns) {
            this.tuples = tuples;
            this.columns = columns;
        }
    }

    @Override
    final ExportContext makeExportContext(final int @NotNull [] columns) {
        return new TupleExportContext(counts.keySet().iterator(), columns);
    }

    @Override
    final boolean exportKeys(@NotNull final ExportContext context, @NotNull final WritableChunk<Values>[] keyChunks) {
        final TupleExportContext tupleContext = (TupleExportContext) context;
        return exportTuples(tupleContext.tuples, tupleContext.columns, keyChunks);
    }

    private void addTuples(@NotNull final ObjectChunk<Object, ? extends Values> tuples) {
        final int tuplesSize = tuples.size();
        for (int ii = 0; ii < tuplesSize; ++ii) {
            final int sizeBefore = counts.size();
            final long oldCount = counts.addTo(tuples.get(ii), 1);
            if (oldCount == 0) {
                // A key at zero is still in the map until finishRemove, so only an insertion grows it.
                if (counts.size() == sizeBefore) {
                    ++revivedKeys;
                } else {
                    ++insertedKeys;
                }
            }
        }
    }

    private void removeTuples(@NotNull final ObjectChunk<Object, ? extends Values> tuples) {
        final int tuplesSize = tuples.size();
        for (int ii = 0; ii < tuplesSize; ++ii) {
            final long oldCount = counts.addTo(tuples.get(ii), -1);
            Assert.gtZero(oldCount, "oldCount");
            if (oldCount == 1) {
                ++emptiedKeys;
            }
        }
    }

    private void dropEmptied(@NotNull final ObjectChunk<Object, ? extends Values> tuples) {
        final int tuplesSize = tuples.size();
        for (int ii = 0; ii < tuplesSize; ++ii) {
            counts.remove(tuples.get(ii), 0L);
        }
    }

    private void forEachTupleChunk(
            @NotNull final RowSequence rows,
            final boolean usePrev,
            @NotNull final Consumer<ObjectChunk<Object, ? extends Values>> action) {
        if (rows.isEmpty()) {
            return;
        }
        final int chunkSize = (int) Math.min(rows.size(), CHUNK_SIZE);
        // @formatter:off
        try (final ColumnSource.GetContext getContext = tupleSource.makeGetContext(chunkSize);
             final RowSequence.Iterator rowsIterator = rows.getRowSequenceIterator()) {
            // @formatter:on
            while (rowsIterator.hasMore()) {
                final RowSequence chunkRows = rowsIterator.getNextRowSequenceWithLength(chunkSize);
                final Chunk<? extends Values> tuples = usePrev
                        ? tupleSource.getPrevChunk(getContext, chunkRows)
                        : tupleSource.getChunk(getContext, chunkRows);
                action.accept(tuples.asObjectChunk());
            }
        }
    }
}
