# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deephaven/proto/object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pydeephaven.proto import ticket_pb2 as deephaven_dot_proto_dot_ticket__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x65\x65phaven/proto/object.proto\x12!io.deephaven.proto.backplane.grpc\x1a\x1c\x64\x65\x65phaven/proto/ticket.proto\"W\n\x12\x46\x65tchObjectRequest\x12\x41\n\tsource_id\x18\x01 \x01(\x0b\x32..io.deephaven.proto.backplane.grpc.TypedTicket\"z\n\x13\x46\x65tchObjectResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12G\n\x0ftyped_export_id\x18\x03 \x03(\x0b\x32..io.deephaven.proto.backplane.grpc.TypedTicket\"V\n\x0e\x43onnectRequest\x12\x44\n\x0ctyped_ticket\x18\x01 \x01(\x0b\x32..io.deephaven.proto.backplane.grpc.TypedTicket\"d\n\x0b\x44\x61taRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12G\n\x0ftyped_export_id\x18\x02 \x03(\x0b\x32..io.deephaven.proto.backplane.grpc.TypedTicket\"\xa3\x01\n\x0eMessageRequest\x12\x46\n\tsource_id\x18\x01 \x01(\x0b\x32\x31.io.deephaven.proto.backplane.grpc.ConnectRequestH\x00\x12>\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32..io.deephaven.proto.backplane.grpc.DataRequestH\x00\x42\t\n\x07payload\"h\n\x0fMessageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12G\n\x0ftyped_export_id\x18\x02 \x03(\x0b\x32..io.deephaven.proto.backplane.grpc.TypedTicket\"\x15\n\x13\x42rowserNextResponse2\x90\x04\n\rObjectService\x12~\n\x0b\x46\x65tchObject\x12\x35.io.deephaven.proto.backplane.grpc.FetchObjectRequest\x1a\x36.io.deephaven.proto.backplane.grpc.FetchObjectResponse\"\x00\x12|\n\rMessageStream\x12\x31.io.deephaven.proto.backplane.grpc.MessageRequest\x1a\x32.io.deephaven.proto.backplane.grpc.MessageResponse\"\x00(\x01\x30\x01\x12~\n\x11OpenMessageStream\x12\x31.io.deephaven.proto.backplane.grpc.MessageRequest\x1a\x32.io.deephaven.proto.backplane.grpc.MessageResponse\"\x00\x30\x01\x12\x80\x01\n\x11NextMessageStream\x12\x31.io.deephaven.proto.backplane.grpc.MessageRequest\x1a\x36.io.deephaven.proto.backplane.grpc.BrowserNextResponse\"\x00\x42\x42H\x01P\x01Z<github.com/deephaven/deephaven-core/go/internal/proto/objectb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deephaven.proto.object_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001P\001Z<github.com/deephaven/deephaven-core/go/internal/proto/object'
  _FETCHOBJECTREQUEST._serialized_start=97
  _FETCHOBJECTREQUEST._serialized_end=184
  _FETCHOBJECTRESPONSE._serialized_start=186
  _FETCHOBJECTRESPONSE._serialized_end=308
  _CONNECTREQUEST._serialized_start=310
  _CONNECTREQUEST._serialized_end=396
  _DATAREQUEST._serialized_start=398
  _DATAREQUEST._serialized_end=498
  _MESSAGEREQUEST._serialized_start=501
  _MESSAGEREQUEST._serialized_end=664
  _MESSAGERESPONSE._serialized_start=666
  _MESSAGERESPONSE._serialized_end=770
  _BROWSERNEXTRESPONSE._serialized_start=772
  _BROWSERNEXTRESPONSE._serialized_end=793
  _OBJECTSERVICE._serialized_start=796
  _OBJECTSERVICE._serialized_end=1324
# @@protoc_insertion_point(module_scope)
