/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jpy_PyLib_CallableKind */

#ifndef _Included_org_jpy_PyLib_CallableKind
#define _Included_org_jpy_PyLib_CallableKind
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
