#!/bin/bash

usage() {
  echo "Usage: $0 [-c]"
  echo "Formats the docs in place using the Salmon formatter."
  echo
  echo "Options:"
  echo "  -c        Run the formatter in check mode (does not modify files)"
  echo "  -h        Show this help message"
}

DPRINT_CMD=fmt
while getopts ":ch" opt; do
  case $opt in
    c)
      DPRINT_CMD="check --allow-no-files"
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac

done

pushd "$(dirname "$0")" > /dev/null # Set pwd to this directory
docker run --rm --name deephaven-docs-formatter --pull=always -e DPRINT_CMD="$DPRINT_CMD" --volume ./python:/format/python --volume ./groovy:/format/groovy ghcr.io/deephaven/salmon-formatter:1
EXIT_CODE=$?
echo Formatting complete. You may need to run 'docs/updateSnapshots' if this reported files were changed.
popd > /dev/null # Reset pwd

exit $EXIT_CODE