#!/bin/bash

usage() {
  echo "Usage: $0 [-t tag] [-a]"
  echo "Updates the docs snapshots for Python and Groovy."
  echo
  echo "Options:"
  echo "  -t tag    The docker tag to use for the community server (default: latest)."
  echo "            Use 'local' to use a local build of the docs server. This will run ./gradlew prepareCompose"
  echo "  -a        Update all snapshots even if they are already up to date."
  echo "  -h        Show this help message"
  echo
  echo "Example:"
  echo "  $0 -t edge"
}

DH_TAG=latest
RUN_ALL=false

while getopts "t:ah" opt; do
  case $opt in
    t)
      DH_TAG=$OPTARG
      ;;
    a)
      RUN_ALL=true
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

DEEPHAVEN_SERVER_IMAGE="ghcr.io/deephaven/server:$DH_TAG"

pushd "$(dirname "$0")" > /dev/null # Set pwd to this directory

if [ "$DH_TAG" = "local" ]; then
  echo "Using local build of the docs server."
  pushd "../" > /dev/null # Move to the root of the project
  ./gradlew prepareCompose
  source .env # Sources from the root of the project for DEEPHAVEN_SERVER_IMAGE variable
  popd > /dev/null
else
  echo "Using Docker tag: $DH_TAG"
fi

DOCKER_CONFIG_DIR=$(realpath "snapshotter/docker")
export DOCKER_CONFIG_DIR
export RUN_ALL
export DEEPHAVEN_SERVER_IMAGE
./format # Format before updating snapshots because the snapshots will be invalid if the content changes from formatting

SNAPSHOT_LANGUAGE=python docker compose -f snapshotter/docker-compose.yml run --rm snapshotter
PY_EXIT_CODE=$?
SNAPSHOT_LANGUAGE=python docker compose -f snapshotter/docker-compose.yml down --volumes

if [ $PY_EXIT_CODE -gt 128 ]; then # Interrupted, don't continue
  popd > /dev/null
  exit $PY_EXIT_CODE
fi

SNAPSHOT_LANGUAGE=groovy docker compose -f snapshotter/docker-compose.yml run --rm snapshotter
GROOVY_EXIT_CODE=$?
SNAPSHOT_LANGUAGE=groovy docker compose -f snapshotter/docker-compose.yml down --volumes

popd > /dev/null # Reset pwd

if [ $PY_EXIT_CODE -ne 0 ]; then
  echo "Python snapshot update failed with exit code $PY_EXIT_CODE. Errors in docs/snapshotter/errors/python/errors.txt"
fi

if [ $GROOVY_EXIT_CODE -ne 0 ]; then
  echo "Groovy snapshot update failed with exit code $GROOVY_EXIT_CODE. Errors in docs/snapshotter/errors/groovy/errors.txt"
fi

if [ $PY_EXIT_CODE -ne 0 ] || [ $GROOVY_EXIT_CODE -ne 0 ]; then
  exit 1
fi

exit 0
