SELECT
  *,
  I + 2 * I - I / 2 as math_i,
  PI as pi,
  RAND() as rand,
  CURRENT_TIMESTAMP as the_timestamp,
  NOT(B) as not_b,
  TRUE as literal_true,
  FALSE as literal_false,
  CAST(1 as BIGINT) as literal_long,
  CAST(1 as INTEGER) as literal_int,
  - I as neg_i,
  I IS NULL as i_is_null,
  I IS NOT NULL as i_is_not_null,
  B IS NULL as b_is_null,
  B IS NOT NULL as b_is_not_null,
  LN(I) as ln_i,
  // LOG10(I) as log_10_i,
  ABS(I) as abs_i,
  SIN(I) as sin_i,
  COS(I) as cos_i,
  TAN(I) as tan_i,
  ASIN(I) as asin_i,
  ACOS(I) as acos_i,
  ATAN(I) as atan_i,
  SIGN(I) as sign_i,
  ROUND(I) as round_i,
  CEIL(I) as ceil_i,
  FLOOR(I) as floor_i,
  EXP(I) as exp_i
  // UNKNOWN as literal_unknown,
  // SQRT(I) as sqrt_i,
FROM
  my_time
