plugins {
    id 'java-library'
    id 'io.deephaven.project.register'
}

description = 'The Deephaven SQL parser'


dependencies {
    api project(':qst')
    implementation libs.calcite.core

    constraints {
        implementation(libs.httpcore5) {
            // used by calcite-core, iceberg, and confluent
            because 'CVE-2026-54399'
        }
        implementation(libs.httpcore5.h2) {
            because 'Keeping consistency with libs.httpcore5'
        }
    }

    compileOnly project(':util-immutables')
    annotationProcessor libs.immutables.value

    testImplementation libs.assertj
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testRuntimeOnly libs.slf4j.simple
}

test {
    useJUnitPlatform()
}
