name: Nightly Image Compare CI

on:
  schedule:
    # 10AM EST == 14 UTC
    - cron:  '0 14 * * *'

jobs:
  compare:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'deephaven' }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup JDKs
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: |
            21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Setup gradle properties
        run: |
          .github/scripts/gradle-properties.sh 21 >> gradle.properties
          cat gradle.properties

      - name: Run gradle
        run: ./gradlew --continue pullImage compareImage

      - name: Notify Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        id: notify-slack
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DHC_NOTIFY }}
        with:
          webhook-type: webhook-trigger
          payload: '{"repository": "${{ github.repository }}", "message": "${{ github.workflow }}/${{ github.job }} failure, some image is out of date", "link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
